### ISSUE TITLE
Concrete powder to concrete type recipe?

### ISSUE THREAD

**Issue by pfgithub** [Insane96/CustomFluidMixin#10]
Any concrete powder touching water turns into concrete. Is there any way to make a recipe like this? The closest I got is

```json
{
    "type": "block_transform",
    "flowing": "minecraft:water",
    "block_to_transform": "minecraft:stone",
    "blocks_nearby": [],
    "result": {
        "type": "block",
        "block": "minecraft:ice"
    }
}
```

But this only transforms next to the source block, not next to flowing liquid

**Comment by Insane96** [comment]
You need to use fluid tags. Also next time use discord/cf comments for questions, this is an issue tracker

**Comment by pfgithub** [comment]
dang, I also missed there was a previous issue # 2 that was basically the same thing.

I don't see a discord link on curseforge or github or on your profile page on either

**Comment by Insane96** [comment]
They're both on the curseforge page
