### ISSUE TITLE
Wiki missing 'fizz' property and uses "fluid_mixin" instead of "flowing_block"

### ISSUE THREAD

**Issue by pfgithub** [Insane96/CustomFluidMixin#11]
https://github.com/Insane96/CustomFluidMixin/wiki

Missing `fizz` in properties

- `fizz`: Optional, default true. Controls if a fizz sound and effect are played when successful

Documentation also suggests 'type' should be "fluid_mixin" or "block_transform" but it seems the correct name is "flowing_block" (in the 'type' and 'blocks_nearby' descriptions)

**Comment by Insane96** [comment]
Thanks, I've updated the wiki adding fizz and cleaning it
