### ISSUE TITLE
want to interact with fluids to fluids

### ISSUE THREAD

**Issue by tamimbook** [Insane96/CustomFluidMixin#14]
Hi, I want to create a custom datapack where two flowing fluids meet and cause a block to form. I’m not sure how to make this, and I would appreciate any help.
![image](https://github.com/user-attachments/assets/1cf98fe2-2329-486c-bef7-62689153ca5d)

**Comment by Insane96** [comment]
This is not an help board.
Also check the wiki: https://github.com/Insane96/CustomFluidMixin/wiki
