### ISSUE TITLE
Recipes don't use "flowing" fluid, instead require source block.

### ISSUE THREAD

**Issue by rovenfaded** [Insane96/CustomFluidMixin#2]
MC: 1.18.2
Mod version: 1.2.0

Any recipes made with "flowing_block" don't actually use the flowing part of the fluid. Instead, they require the source block. Since this uses up the fluid, the generator function of the recipe no longer works.

The recipes can find the different blocks and fluids without problem. The recipes also work for the most part. The only problem is that you can't use flowing fluids, but are required to use the source block instead.

**Comment by Insane96** [comment]
Pls send the datapack you're using

**Comment by Insane96** [comment]
Just realized, you need to use the tag e.g. `#minecraft:lava` that targets both fluid and flowing
