### ISSUE TITLE
[1.19.2] Recipes are blinking.

### ISSUE THREAD

**Issue by murao-kun** [Insane96/CustomFluidMixin#3]
On 1.19.2 jei integration have some blinking issues.
![image](https://user-images.githubusercontent.com/110398598/184256396-a8d827d6-243f-4532-b8b4-fca967a14374.png)
![image](https://user-images.githubusercontent.com/110398598/184256438-d9b9b283-e382-4678-84e7-832a7db221d5.png)

**Comment by Insane96** [comment]
Update to InsaneLib 1.6.1
