### ISSUE TITLE
Compatability Request: Roughly Enough Items

### ISSUE THREAD

**Issue by PurpleDeving** [Insane96/CustomFluidMixin#7]
Hi,

i tried using REI with Custom Fluid Mixin and that doesnt work.

Version used: 1.20.1 > Custom Fluid 1.4.0

Mods used:
REI
REI dependency > Architectury API
REI dependency > Cloth Config
REI dependency > REI Plugin Compatabilities
Custom Fluid Mixin + InsaneLib

Expected behavior:
Custom Fluid Mixin and REI working 

Current behavior:
REI does not show up in the inventory. Its still loaded (you can edit the config over the mod config menu)
Unkown if Custom Fluid Mixin work - have not testet that

[latest.log](https://github.com/Insane96/CustomFluidMixin/files/13197832/latest.log)
[rei.log](https://github.com/Insane96/CustomFluidMixin/files/13197835/rei.log)

**Comment by Insane96** [comment]
Try without the plugin compat. I have no reason to think why this shouldn't work.

**Comment by PurpleDeving** [comment]
The REI Compatability Plugin is a hard dependency of REI itself. It cannot run without it. 

You can pretty easily test it with just a simple setup like below.

But ofc this might be a bug that needs to be fixed on the side of shedaniel. I dont know that.

![grafik](https://github.com/Insane96/CustomFluidMixin/assets/111588944/b3553d2b-3718-4f69-9290-d291061f7b6c)

**Comment by Insane96** [comment]
Wait, JEI plugins work with REI?

EDIT: Wait, try downgrading InsaneLib to the latest 1.11.x

**Comment by PurpleDeving** [comment]
Yeah, usually JEI plugins (like Just Enough Resources, Just Enough Mekanism Multiblocks etc.) work with REI, given it tries to get them all working with the compatability plugin.

I tried using the InsaneLib Version 1.12.0-mc.1.20.1 and now the the 1.11.1-mc1.20.1
Booth result in the complete disapearance of REI.

![grafik](https://github.com/Insane96/CustomFluidMixin/assets/111588944/aeadb2d5-e7f3-426f-93f8-b59c5d46ae51)
![grafik](https://github.com/Insane96/CustomFluidMixin/assets/111588944/c8618477-0ed3-461a-9e0c-ed7244a2a983)

**Comment by Insane96** [comment]
Try 1.10.x

**Comment by PurpleDeving** [comment]
Yes, it seems like 1.10.1 (havnt yet testet 1.10.2) does work (at least in the REI part). Havnt yet checkef if custom fluid mixin "recipes" are shown correctly.

**Comment by Insane96** [comment]
Nice, thanks for testing, I've released a new version that should work with latest InsaneLib.
